Create Connect Activity
Lumenaries/LumenOS pull request #49
Opened 2024-04-16 21:15 UTC by jennaluz

This activity will handle the layout of the display upon user connection and disconnection to the access point.

2024-04-16 21:54 UTC, jennaluz commented on src/lumen/button_callback.hpp
> +
- [x] Add comment

2024-04-16 22:05 UTC, loganfin requested changes

2024-04-16 22:05 UTC, loganfin commented on src/lumen/activity/connect.cpp
> +    : ssid_{reinterpret_cast<char const*>(CONFIG_NET_WIFI_SSID)},
Remove the `reinterpret_cast`s here and initialize these members in the class. Then you should be able to remove this constructor.

2024-04-16 22:05 UTC, loganfin commented on src/lumen/activity/connect.cpp
> +    ESP_LOGI(tag, "Setting up connection %d", connected);
Remove this debug statement.

2024-04-16 22:05 UTC, loganfin commented on src/lumen/activity/connect.cpp
> +    display->setTextColor(hardware::Display::color565(255, 128, 0));
Not important now, but in the future we might want to have some theme-specific color values so we can do something like:

```
display->setTextColor(hardware::Display::Color::text);
```

2024-04-16 22:05 UTC, loganfin commented on src/lumen/activity/connect.hpp
> +    Connect();
Remove the constructor and initialize the member variables here.

2024-04-16 22:05 UTC, loganfin commented on src/lumen/net/wifi.cpp
> +    ESP_LOGI(tag, "Randomize softAP password");
I don't think we need this.

2024-04-16 22:05 UTC, loganfin commented on src/lumen/net/wifi.cpp
> +    ESP_LOGI(tag, "New password: %s", password);
I don't think we need this either.

2024-04-16 22:05 UTC, loganfin commented on src/lumen/net/wifi.hpp
> +void init_wifi(activity::Context& activity_context);
Add some comments here.

2024-04-17 02:10 UTC, jennaluz commented on src/lumen/net/wifi.cpp
> +
- [x] Add comments

2024-04-17 02:12 UTC, loganfin requested changes

2024-04-17 02:12 UTC, loganfin commented on src/lumen/button_callback.hpp
> + * \param button The handle to the button.
Is this accurate?

2024-04-17 02:27 UTC, loganfin approved these changes

2024-04-17 02:59 UTC, merged